name: ExpenseTracker
description: A Flutter application for tracking expenses.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.3 # Para manejar el estado
  sqflite: ^2.0.0+4
  path_provider: ^2.0.2
  fl_chart: ^0.50.0
  flutter_speed_dial: ^5.0.0
  csv: ^5.0.0
  share_plus: ^6.3.0
  flutter_local_notifications: ^14.0.0
  timezone: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  hive_generator: ^1.1.3
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/